// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ZmRaaYe6r7xlAZjVBj6dQ1VLbymx4wg',
    appId: '1:488040137399:web:a9eeb944bf09a94b118332',
    messagingSenderId: '488040137399',
    projectId: 'contrast-6b1c8',
    authDomain: 'contrast-6b1c8.firebaseapp.com',
    storageBucket: 'contrast-6b1c8.appspot.com',
    measurementId: 'G-2YKNKLTHBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAdeMv73m6t0qCJz73KG5xKmCBwUY9tyo',
    appId: '1:488040137399:android:b7d9e9331f14bffd118332',
    messagingSenderId: '488040137399',
    projectId: 'contrast-6b1c8',
    storageBucket: 'contrast-6b1c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jMcbBA16SVpPTSSNTbb24n4MhkIsy0k',
    appId: '1:488040137399:ios:81656b6cb2424cd0118332',
    messagingSenderId: '488040137399',
    projectId: 'contrast-6b1c8',
    storageBucket: 'contrast-6b1c8.appspot.com',
    iosClientId: '488040137399-pa9ir3e3jqbsp3lmc4b8e9fl2o4lf7gg.apps.googleusercontent.com',
    iosBundleId: 'eu.bsdsoft.contrast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4jMcbBA16SVpPTSSNTbb24n4MhkIsy0k',
    appId: '1:488040137399:ios:c2ffc3bb561e644a118332',
    messagingSenderId: '488040137399',
    projectId: 'contrast-6b1c8',
    storageBucket: 'contrast-6b1c8.appspot.com',
    iosClientId: '488040137399-fns2lurdfm59s97mpp4qcevfu3rddrjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.contrast.RunnerTests',
  );
}
